# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: titanium.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='titanium.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0etitanium.proto\x1a\x0cnanopb.proto\"B\n\x12NetworkCredentials\x12\x13\n\x04ssid\x18\x01 \x01(\tB\x05\x92?\x02\x08 \x12\x17\n\x08password\x18\x02 \x01(\tB\x05\x92?\x02\x08@\"a\n\x12NetworkInformation\x12$\n\x0c\x61p_connected\x18\x01 \x01(\x0e\x32\x0e.NetworkStatus\x12%\n\rsta_connected\x18\x02 \x01(\x0e\x32\x0e.NetworkStatus\"*\n\x0c\x42rokerConfig\x12\x1a\n\nbroker_uri\x18\x01 \x01(\tB\x06\x92?\x03\x08\x80\x02\"\xae\x01\n\rPacketRequest\x12\x1b\n\x13\x64\x65stination_address\x18\x01 \x01(\x05\x12&\n\x10\x64\x65stination_area\x18\x02 \x01(\x0e\x32\x0c.MemoryAreas\x12$\n\x0erequested_area\x18\x03 \x01(\x0e\x32\x0c.MemoryAreas\x12\x17\n\x0fpacket_interval\x18\x04 \x01(\r\x12\x19\n\x11last_transmission\x18\x05 \x01(\x04\"D\n\x13\x43ontinuosPacketList\x12-\n\x0epacket_configs\x18\x01 \x03(\x0b\x32\x0e.PacketRequestB\x05\x92?\x02\x10\x08*0\n\rNetworkStatus\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\r\n\tCONNECTED\x10\x01*\xd2\x01\n\x0bMemoryAreas\x12\x17\n\x13NETWORK_CREDENTIALS\x10\x00\x12\x17\n\x13NETWORK_INFORMATION\x10\x01\x12\x11\n\rBROKER_CONFIG\x10\x02\x12\x18\n\x14\x43OMMUNICATION_CONFIG\x10\x03\x12\x16\n\x12UART_SINGLE_PACKET\x10\x04\x12\x19\n\x15UART_CONTINUOS_PACKET\x10\x05\x12\x16\n\x12LORA_SINGLE_PACKET\x10\x06\x12\x19\n\x15LORA_CONTINUOS_PACKET\x10\x07\x62\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])

_NETWORKSTATUS = _descriptor.EnumDescriptor(
  name='NetworkStatus',
  full_name='NetworkStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=490,
  serialized_end=538,
)
_sym_db.RegisterEnumDescriptor(_NETWORKSTATUS)

NetworkStatus = enum_type_wrapper.EnumTypeWrapper(_NETWORKSTATUS)
_MEMORYAREAS = _descriptor.EnumDescriptor(
  name='MemoryAreas',
  full_name='MemoryAreas',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NETWORK_CREDENTIALS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NETWORK_INFORMATION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BROKER_CONFIG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMUNICATION_CONFIG', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UART_SINGLE_PACKET', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UART_CONTINUOS_PACKET', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LORA_SINGLE_PACKET', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LORA_CONTINUOS_PACKET', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=541,
  serialized_end=751,
)
_sym_db.RegisterEnumDescriptor(_MEMORYAREAS)

MemoryAreas = enum_type_wrapper.EnumTypeWrapper(_MEMORYAREAS)
DISCONNECTED = 0
CONNECTED = 1
NETWORK_CREDENTIALS = 0
NETWORK_INFORMATION = 1
BROKER_CONFIG = 2
COMMUNICATION_CONFIG = 3
UART_SINGLE_PACKET = 4
UART_CONTINUOS_PACKET = 5
LORA_SINGLE_PACKET = 6
LORA_CONTINUOS_PACKET = 7



_NETWORKCREDENTIALS = _descriptor.Descriptor(
  name='NetworkCredentials',
  full_name='NetworkCredentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssid', full_name='NetworkCredentials.ssid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\010 '), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='NetworkCredentials.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\010@'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=98,
)


_NETWORKINFORMATION = _descriptor.Descriptor(
  name='NetworkInformation',
  full_name='NetworkInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ap_connected', full_name='NetworkInformation.ap_connected', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sta_connected', full_name='NetworkInformation.sta_connected', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=197,
)


_BROKERCONFIG = _descriptor.Descriptor(
  name='BrokerConfig',
  full_name='BrokerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='broker_uri', full_name='BrokerConfig.broker_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\003\010\200\002'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=241,
)


_PACKETREQUEST = _descriptor.Descriptor(
  name='PacketRequest',
  full_name='PacketRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='destination_address', full_name='PacketRequest.destination_address', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_area', full_name='PacketRequest.destination_area', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requested_area', full_name='PacketRequest.requested_area', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packet_interval', full_name='PacketRequest.packet_interval', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_transmission', full_name='PacketRequest.last_transmission', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=418,
)


_CONTINUOSPACKETLIST = _descriptor.Descriptor(
  name='ContinuosPacketList',
  full_name='ContinuosPacketList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet_configs', full_name='ContinuosPacketList.packet_configs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\020\010'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=488,
)

_NETWORKINFORMATION.fields_by_name['ap_connected'].enum_type = _NETWORKSTATUS
_NETWORKINFORMATION.fields_by_name['sta_connected'].enum_type = _NETWORKSTATUS
_PACKETREQUEST.fields_by_name['destination_area'].enum_type = _MEMORYAREAS
_PACKETREQUEST.fields_by_name['requested_area'].enum_type = _MEMORYAREAS
_CONTINUOSPACKETLIST.fields_by_name['packet_configs'].message_type = _PACKETREQUEST
DESCRIPTOR.message_types_by_name['NetworkCredentials'] = _NETWORKCREDENTIALS
DESCRIPTOR.message_types_by_name['NetworkInformation'] = _NETWORKINFORMATION
DESCRIPTOR.message_types_by_name['BrokerConfig'] = _BROKERCONFIG
DESCRIPTOR.message_types_by_name['PacketRequest'] = _PACKETREQUEST
DESCRIPTOR.message_types_by_name['ContinuosPacketList'] = _CONTINUOSPACKETLIST
DESCRIPTOR.enum_types_by_name['NetworkStatus'] = _NETWORKSTATUS
DESCRIPTOR.enum_types_by_name['MemoryAreas'] = _MEMORYAREAS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetworkCredentials = _reflection.GeneratedProtocolMessageType('NetworkCredentials', (_message.Message,), dict(
  DESCRIPTOR = _NETWORKCREDENTIALS,
  __module__ = 'titanium_pb2'
  # @@protoc_insertion_point(class_scope:NetworkCredentials)
  ))
_sym_db.RegisterMessage(NetworkCredentials)

NetworkInformation = _reflection.GeneratedProtocolMessageType('NetworkInformation', (_message.Message,), dict(
  DESCRIPTOR = _NETWORKINFORMATION,
  __module__ = 'titanium_pb2'
  # @@protoc_insertion_point(class_scope:NetworkInformation)
  ))
_sym_db.RegisterMessage(NetworkInformation)

BrokerConfig = _reflection.GeneratedProtocolMessageType('BrokerConfig', (_message.Message,), dict(
  DESCRIPTOR = _BROKERCONFIG,
  __module__ = 'titanium_pb2'
  # @@protoc_insertion_point(class_scope:BrokerConfig)
  ))
_sym_db.RegisterMessage(BrokerConfig)

PacketRequest = _reflection.GeneratedProtocolMessageType('PacketRequest', (_message.Message,), dict(
  DESCRIPTOR = _PACKETREQUEST,
  __module__ = 'titanium_pb2'
  # @@protoc_insertion_point(class_scope:PacketRequest)
  ))
_sym_db.RegisterMessage(PacketRequest)

ContinuosPacketList = _reflection.GeneratedProtocolMessageType('ContinuosPacketList', (_message.Message,), dict(
  DESCRIPTOR = _CONTINUOSPACKETLIST,
  __module__ = 'titanium_pb2'
  # @@protoc_insertion_point(class_scope:ContinuosPacketList)
  ))
_sym_db.RegisterMessage(ContinuosPacketList)


_NETWORKCREDENTIALS.fields_by_name['ssid']._options = None
_NETWORKCREDENTIALS.fields_by_name['password']._options = None
_BROKERCONFIG.fields_by_name['broker_uri']._options = None
_CONTINUOSPACKETLIST.fields_by_name['packet_configs']._options = None
# @@protoc_insertion_point(module_scope)
